image:
  file: .gitpod.Dockerfile

tasks:
  - command: |
      cd services/website
      gp await-port 3000
      npm run cy:run
      cd services/events-api/ya-load-testing
      gp await-port 8123
      ./bin/run -d dev.com
    env:
      CYPRESS_CACHE_FOLDER: /workspace/.cache/cypress
  - init: npm install
    command: |
      export HMR_HOST=`gp url 3000`
      FAUNADB_ADMIN_SECRET=$YA_FAUNADB_ADMIN_SECRET FAUNADB_SERVER_SECRET=$YA_FAUNADB_SERVER_SECRET MAGIC_SECRET_KEY=$YA_MAGIC_SECRET_KEY npm run dev
    env:
      CYPRESS_CACHE_FOLDER: /workspace/.cache/cypress
  - command: cd services/db-analytics/dev/db && clickhouse-server
ports:
  - port: 3000
    onOpen: ignore
    visibility: public
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore
  - port: 8080-8082
    onOpen: ignore
    visibility: public
  - port: 8123
    onOpen: ignore
  - port: 9000
    onOpen: ignore
  - port: 9004
    onOpen: ignore
  - port: 10000
    onOpen: ignore

vscode:
  extensions:
    - svelte.svelte-vscode
    - bradlc.vscode-tailwindcss
