 steps:
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/events-api:$COMMIT_SHA', '.']
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/events-api:$COMMIT_SHA']
 - name: 'gcr.io/cloud-builders/gcloud'
   args:
   - 'run'
   - 'deploy'
   - 'events-api'
   - '--image'
   - 'gcr.io/$PROJECT_ID/events-api:$COMMIT_SHA'
   - '--region'
   - 'us-central-1'
   - '--platform'
   - 'managed'
   - '--vpc-connector'
   - 'cloud-run-vpc-connector'
   dir: 'services/events-api'
   env:
   - 'CH_HOST=$_CH_HOST'
   - 'CH_PORT=$_CH_PORT'
   - 'CH_USER=$_CH_USER'
   - 'CH_PASSWORD=$_CH_PASSWORD'
 images:
 - 'gcr.io/$PROJECT_ID/events-api:$COMMIT_SHA'