steps:
  - name: "bash"
    args: ["mkdir", "local-packages"]
    dir: "services/events-api"
  - name: "bash"
    args: ["cp", "-r", "../../packages/clickhouse", "local-packages/"]
    dir: "services/events-api"
  - name: "ubuntu"
    entrypoint: bash
    args:
      - "-c"
      - |
        sed -i "s|YOUR_ACCOUNT_ID_HERE|$_MAXMIND_ACCOUNT_ID |g" ./GeoIP.conf
        sed -i "s|YOUR_LICENSE_KEY_HERE|$_MAXMIND_LICENSE_KEY |g" ./GeoIP.conf
    dir: "services/events-api/geo-db"
  - name: "gcr.io/your-analytics/maxmind-geoipupdater:latest"
    dir: "services/events-api/geo-db"
  - name: "bash"
    args: ["test", "-f", "GeoLite2-City.mmdb"]
    dir: "services/events-api/geo-db"
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/events-api:$COMMIT_SHA", "."]
    dir: "services/events-api"
  - name: "bash"
    args: ["rm", "-fr", "local-packages"]
    dir: "services/events-api"
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/events-api:$COMMIT_SHA"]
    dir: "services/events-api"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "beta"
      - "run"
      - "deploy"
      - "events-api"
      - "--image"
      - "gcr.io/$PROJECT_ID/events-api:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--vpc-connector"
      - "cloud-run-vpc-connector"
      - "--allow-unauthenticated"
      - "--set-env-vars"
      - "CH_HOST=$_CH_HOST,CH_PORT=$_CH_PORT,CH_USER=$_CH_USER,CH_PASSWORD=$_CH_PASSWORD,NODE_ENV=production"
    dir: "services/events-api"
images:
  - "gcr.io/$PROJECT_ID/events-api:$COMMIT_SHA"
